api_gateway_url = "https://<api-id>.execute-api.us-east-1.amazonaws.com"
api_gateway_token = "<shared-token>"

[trii_backend]
api_gateway_url = "https://<api-id>.execute-api.us-east-1.amazonaws.com"
api_gateway_token = "<shared-token>"
